export type MemberRole = 'OWNER' | 'EDITOR' | 'VIEWER';
export type AssetCategory = 'CASH' | 'INVESTMENT' | 'CRYPTO' | 'REAL_ESTATE' | 'PENSION' | 'LIABILITY';
export type TxType = 'INCOME' | 'EXPENSE';
export type CategoryType = 'INCOME' | 'EXPENSE';
export type CostType = 'FIXED' | 'VARIABLE';
export type RecurringFrequency = 'MONTHLY' | 'YEARLY';

export interface Asset {
  id: number;
  householdId: number;
  name: string;
  category: AssetCategory;
  currency: string;
  isLiability: boolean;
  ownerUserId: number | null;
  archivedAt: string | null;
  latestSnapshot?: { value: number; valueKRW: number; date: string };
}

export interface AssetSnapshot {
  id: number;
  assetId: number;
  date: string;
  value: number;
  fxRateToKRW: number;
  valueKRW: number;
}

export interface Category {
  id: number;
  householdId: number | null;
  type: CategoryType;
  name: string;
  icon: string;
  color: string | null;
  parentId: number | null;
  isBuiltin: boolean;
  defaultCostType?: CostType | null;
}

export interface CategoryIconAsset {
  id: number;
  url: string;
  filename: string;
  createdAt: string;
}

export interface Transaction {
  id: number;
  householdId: number;
  date: string;
  type: TxType;
  amount: number;
  currency: string;
  memo: string | null;
  categoryId: number | null;
  category?: Category;
  fromAssetId: number | null;
  toAssetId: number | null;
  tags: string[];
  autoGenerated: boolean;
  costType?: CostType | null;
}

export interface RecurringTransaction {
  id: number;
  householdId: number;
  name: string;
  type: TxType;
  amount: number;
  currency: string;
  categoryId: number | null;
  category?: Category;
  fromAssetId: number | null;
  toAssetId: number | null;
  frequency: RecurringFrequency;
  dayOfMonth: number;
  monthOfYear: number | null;
  startDate: string;
  endDate: string | null;
  active: boolean;
  lastRunDate: string | null;
}

export interface MissedOccurrence {
  recurringId: number;
  date: string;
  type: TxType;
  amount: number;
  title: string | null;
  memo: string | null;
  categoryId: number | null;
  fromAssetId: number | null;
  toAssetId: number | null;
}

export interface Member {
  id: number;
  userId: number;
  user: { id: number; name: string; avatarColor: string; initial: string };
  role: MemberRole;
}

export interface Invitation {
  id: number;
  code: string;
  role: MemberRole;
  expiresAt: string;
  householdId: number;
}

export interface McpToken {
  id: number;
  token: string;
  label: string | null;
  lastUsedAt: string | null;
  createdAt: string;
  connectorUrl: string;
}
