import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsArray,
  IsBoolean,
  IsDateString,
  IsEnum,
  IsNumber,
  IsOptional,
  IsPositive,
  IsString,
  MaxLength,
} from 'class-validator';
import { TransactionType } from '../../entities/transaction.entity';
import { CostType } from '@ad/modules/categories/entities/category.entity';

export class CreateTransactionDto {
  @ApiProperty({ description: '날짜 (YYYY-MM-DD)', example: '2024-01-15' })
  @IsDateString()
  date: string;

  @ApiProperty({ enum: TransactionType })
  @IsEnum(TransactionType)
  type: TransactionType;

  @ApiProperty({ description: '금액 (원화 기준)', example: 300000 })
  @IsNumber()
  @IsPositive()
  amount: number;

  @ApiPropertyOptional({ description: '카테고리 ID' })
  @IsOptional()
  @IsNumber()
  categoryId?: number;

  @ApiPropertyOptional({ description: '출금 자산 ID (지출/이체)' })
  @IsOptional()
  @IsNumber()
  fromAssetId?: number;

  @ApiPropertyOptional({ description: '입금 자산 ID (수입/이체)' })
  @IsOptional()
  @IsNumber()
  toAssetId?: number;

  @ApiPropertyOptional({ description: '제목', maxLength: 200 })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  title?: string;

  @ApiPropertyOptional({ description: '메모' })
  @IsOptional()
  @IsString()
  memo?: string;

  @ApiPropertyOptional({ description: '태그 목록', type: [String] })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  tags?: string[];

  @ApiPropertyOptional({ description: '정기거래 템플릿 ID' })
  @IsOptional()
  @IsNumber()
  recurringTemplateId?: number;

  @ApiPropertyOptional({ description: '자동 생성 여부', default: false })
  @IsOptional()
  @IsBoolean()
  autoGenerated?: boolean;

  @ApiPropertyOptional({ enum: CostType, description: '고정비/변동비 분류 (지출에만 의미 있음, 카테고리 기본값으로 자동 채워지되 거래별 수정 가능)' })
  @IsOptional()
  @IsEnum(CostType)
  costType?: CostType;
}
