import { useEffect, useLayoutEffect, useMemo, useState } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import CategoryIcon from '../../components/common/CategoryIcon';
import EmptyState from '../../components/common/EmptyState';
import Loader from '../../components/ui/Loader';
import ListRow from '../../components/ui/ListRow';
import Border from '../../components/ui/Border';
import ActionSheet from '../../components/common/ActionSheet';
import ConfirmDialog from '../../components/common/ConfirmDialog';
import AppToast from '../../components/common/AppToast';
import { useTheme } from '../../lib/theme';
import { useAuthStore } from '../../stores/auth.store';
import { useHouseholdData, type HouseholdTransaction } from '../../queries/useHouseholdData';
import { useDeleteTx } from '../../queries/mutations';
import { qk } from '../../queries/keys';
import { txApi } from '../../api';
import { resolveCategoryVisual } from '../../lib/category-meta';
import { krw } from '../../lib/format';
import { TE } from '../../lib/toss-emoji';
import type { MoreStackParamList } from '../../navigation/types';
import type { Transaction } from '../../types/api';

type Props = NativeStackScreenProps<MoreStackParamList, 'CategoryTransactions'>;

export default function CategoryTransactionsScreen({ navigation, route }: Props) {
  const { categoryId, categoryName, from, to } = route.params;
  const theme = useTheme();
  const currentHousehold = useAuthStore((s) => s.currentHousehold);
  const hid = currentHousehold?.id;
  const isViewer = currentHousehold?.role === 'VIEWER';
  const canEdit = !isViewer;
  const data = useHouseholdData();
  const deleteTx = useDeleteTx();

  const [actionTx, setActionTx] = useState<HouseholdTransaction | null>(null);
  const [deleteTxState, setDeleteTxState] = useState<HouseholdTransaction | null>(null);
  const [toast, setToast] = useState('');
  const [refreshing, setRefreshing] = useState(false);

  useLayoutEffect(() => {
    navigation.setOptions({ title: categoryName });
  }, [navigation, categoryName]);

  useEffect(() => {
    if (!route.params.savedMode) return;
    const label = { create: '거래를 저장했어요', edit: '거래를 수정했어요', delete: '거래를 삭제했어요' }[route.params.savedMode];
    setToast(label);
    navigation.setParams({ savedMode: undefined, savedAt: undefined });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [route.params.savedAt]);

  // 대분류를 탭한 경우 그 아래 소분류 거래까지 함께 조회(현금흐름 breakdown이 대분류 기준으로 합산되므로 상세 화면도 맞춰야 함)
  const childIds = categoryId != null ? data.categories.filter((c) => c.parentId === categoryId).map((c) => c.id) : [];
  const categoryIds = categoryId != null ? [categoryId, ...childIds] : undefined;
  const params = { from, to, type: 'EXPENSE' as const, limit: 1000, ...(categoryIds ? { categoryIds } : {}) };
  const txQ = useQuery({
    queryKey: qk.transactions(hid ?? 0, params),
    queryFn: () => txApi.search(hid!, params),
    enabled: !!hid,
  });

  async function onRefresh() {
    setRefreshing(true);
    try {
      await Promise.all([data.refetch(), txQ.refetch()]);
    } finally {
      setRefreshing(false);
    }
  }

  // axios 응답 인터셉터가 {success, data, total} 봉투를 이미 data로 벗겨내므로 txQ.data는 배열 자체 — useHouseholdData.ts와 동일 방어 처리
  const raw: Transaction[] = Array.isArray(txQ.data) ? txQ.data : ((txQ.data as any)?.data ?? []);
  const rows: Transaction[] = categoryId == null ? raw.filter((t) => t.categoryId == null) : raw;
  const total = rows.reduce((s, t) => s + Number(t.amount), 0);

  const grouped = useMemo(() => {
    const map = new Map<string, Transaction[]>();
    for (const t of rows) map.set(t.date, [...(map.get(t.date) ?? []), t]);
    return [...map.entries()];
  }, [rows]);

  const visual = resolveCategoryVisual(categoryId, categoryName, data.categories);

  function toEditTx(t: Transaction): HouseholdTransaction {
    const catName = data.categories.find((c) => c.id === t.categoryId)?.name ?? categoryName;
    const rawTitle = (t as unknown as { title?: string }).title;
    return {
      id: String(t.id),
      date: t.date,
      type: t.type,
      amount: Number(t.amount) || 0,
      category: catName,
      categoryId: t.categoryId,
      title: rawTitle || t.memo || catName,
      rawTitle: rawTitle || undefined,
      memo: t.memo ?? undefined,
      from: t.fromAssetId != null ? String(t.fromAssetId) : undefined,
      to: t.toAssetId != null ? String(t.toAssetId) : undefined,
      auto: t.autoGenerated ?? false,
      costType: t.costType ?? null,
    };
  }

  function handleTxAction(value: string) {
    const t = actionTx;
    setActionTx(null);
    if (!t) return;
    if (value === 'edit') {
      navigation.navigate('TransactionEdit', { mode: 'edit', txId: t.id, returnTo: 'CategoryTransactions' });
    } else if (value === 'delete') setDeleteTxState(t);
  }

  async function confirmDeleteTx() {
    if (!deleteTxState) return;
    try {
      await deleteTx.mutateAsync(Number(deleteTxState.id));
      setToast('거래를 삭제했어요');
    } catch {
      setToast('삭제에 실패했어요');
    } finally {
      setDeleteTxState(null);
    }
  }

  if (txQ.isLoading) {
    return (
      <View style={[styles.center, { backgroundColor: theme.bg }]}>
        <Loader size="large" />
      </View>
    );
  }

  return (
    <>
      <ScrollView
        style={[styles.root, { backgroundColor: theme.bg }]}
        contentContainerStyle={{ paddingBottom: 32 }}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={theme.brand} colors={[theme.brand]} />}
      >
        <View style={[styles.summaryCard, { backgroundColor: theme.card, borderColor: theme.border }]}>
        <CategoryIcon icon={visual.icon} size={36} bg={visual.color + '22'} />
        <View style={{ flex: 1 }}>
          <Text style={{ color: theme.text, fontSize: 15, fontWeight: '700' }}>{categoryName}</Text>
          <Text style={{ color: theme.textMuted, fontSize: 12 }}>{rows.length}건</Text>
        </View>
        <Text style={{ color: theme.danger, fontSize: 17, fontWeight: '800' }}>{krw(total)}</Text>
      </View>

      <View style={styles.sectionPad}>
        {rows.length === 0 ? (
          <EmptyState iconCode={TE.receipt} title="이 기간에 해당 카테고리 거래가 없어요" />
        ) : (
          grouped.map(([date, txs]) => (
            <View key={date} style={{ marginBottom: 12 }}>
              <Text style={[styles.dayTitle, { color: theme.textMuted }]}>
                {Number(date.slice(5, 7))}월 {Number(date.slice(8, 10))}일
              </Text>
              <View style={[styles.dayCard, { backgroundColor: theme.card, borderColor: theme.border }]}>
                {txs.map((t, i) => {
                  const rowVisual = resolveCategoryVisual(t.categoryId, categoryName, data.categories);
                  const rowRawTitle = (t as unknown as { title?: string }).title;
                  const rowCatName = data.categories.find((c) => c.id === t.categoryId)?.name ?? categoryName;
                  const rowTitle = rowRawTitle || t.memo || rowCatName;
                  return (
                  <View key={t.id}>
                    <ListRow
                      left={
                        <View style={[styles.itemIcon, { backgroundColor: theme.bg }]}>
                          <CategoryIcon icon={rowVisual.icon} size={18} />
                        </View>
                      }
                      contents={
                        <View>
                          <Text style={{ color: theme.text, fontSize: 14, fontWeight: '600' }}>{rowTitle}</Text>
                          <Text style={{ color: theme.textMuted, fontSize: 11 }}>{rowCatName}</Text>
                        </View>
                      }
                      right={
                        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}>
                          <Text style={{ color: theme.text, fontSize: 14, fontWeight: '700' }}>{krw(t.amount)}</Text>
                          {canEdit && (
                            <Pressable hitSlop={8} onPress={() => setActionTx(toEditTx(t))}>
                              <Text style={{ color: theme.textMuted, fontSize: 18, fontWeight: '700' }}>⋯</Text>
                            </Pressable>
                          )}
                        </View>
                      }
                      onPress={() => navigation.navigate('TransactionDetail', { id: String(t.id) })}
                      verticalPadding="small"
                    />
                    {i < txs.length - 1 && <Border type="full" />}
                  </View>
                  );
                })}
              </View>
            </View>
          ))
        )}
      </View>
      </ScrollView>

      <ActionSheet
        visible={!!actionTx}
        title={actionTx?.title}
        items={[
          { iconCode: TE.pencil, label: '거래 수정', value: 'edit' },
          { iconCode: TE.trash, label: '거래 삭제', value: 'delete', danger: true },
        ]}
        onSelect={handleTxAction}
        onClose={() => setActionTx(null)}
      />
      <ConfirmDialog
        visible={!!deleteTxState}
        title="거래를 삭제할까요?"
        confirmText="삭제하기"
        danger
        loading={deleteTx.isPending}
        onConfirm={confirmDeleteTx}
        onClose={() => setDeleteTxState(null)}
      />
      <AppToast open={!!toast} text={toast} onClose={() => setToast('')} />
    </>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  summaryCard: { flexDirection: 'row', alignItems: 'center', gap: 12, margin: 20, marginBottom: 8, borderRadius: 16, borderWidth: 1, padding: 16 },
  sectionPad: { paddingHorizontal: 20, paddingTop: 12 },
  dayTitle: { fontSize: 12, fontWeight: '700', marginBottom: 8 },
  dayCard: { borderRadius: 14, borderWidth: 1, overflow: 'hidden' },
  itemIcon: { width: 32, height: 32, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },
});
