import { Column, Entity, Index } from 'typeorm';
import { BaseEntity } from '@common/entities/base.entity';
import { CostType } from '@ad/modules/categories/entities/category.entity';

export enum TransactionType {
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE',
}

@Entity('transactions', { schema: 'ad' })
@Index(['householdId', 'date'])
export class Transaction extends BaseEntity {
  @Column({ name: 'household_id' })
  householdId: number;

  @Column({ type: 'date' })
  date: string;

  @Column({ type: 'enum', enum: TransactionType })
  type: TransactionType;

  @Column({ type: 'decimal', precision: 20, scale: 2 })
  amount: number;

  @Column({ name: 'category_id', nullable: true })
  categoryId: number;

  @Column({ name: 'cost_type', type: 'enum', enum: CostType, nullable: true })
  costType?: CostType | null;

  @Column({ name: 'from_asset_id', nullable: true })
  fromAssetId: number;

  @Column({ name: 'to_asset_id', nullable: true })
  toAssetId: number;

  @Column({ length: 200, nullable: true })
  title: string;

  @Column({ type: 'text', nullable: true })
  memo: string;

  @Column({ type: 'simple-array', nullable: true })
  tags: string[];

  @Column({ type: 'jsonb', nullable: true })
  attachments: object[];

  @Column({ name: 'recurring_template_id', nullable: true })
  recurringTemplateId: number;

  @Column({ name: 'auto_generated', default: false })
  autoGenerated: boolean;

  @Column({ name: 'created_by_user_id', nullable: true })
  createdByUserId: number;
}
