/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _404Route } from '../pages/_404';
import { Route as _AboutRoute } from '../pages/about';
import { Route as _FaqRoute } from '../pages/faq';
import { Route as _IndexRoute } from '../pages/';
import { Route as _PortfolioIndexRoute } from '../pages/portfolio';
import { Route as _PortfolioIdRoute } from '../pages/portfolio/[id]';
import { Route as _QuoteBuilderRoute } from '../pages/quote/builder';
import { Route as _QuoteIdRoute } from '../pages/quote/[id]';
import { Route as _ReservationIndexRoute } from '../pages/reservation';
import { Route as _ReservationSearchRoute } from '../pages/reservation/search';
import { Route as _ReviewsIndexRoute } from '../pages/reviews';
import { Route as _ReviewsWriteReservationIdRoute } from '../pages/reviews/write/[reservationId]';
import { Route as _UnauthorizedRoute } from '../pages/unauthorized';
import { Route as _MyIndexRoute } from '../pages/my';
import { Route as _MyReservationsRoute } from '../pages/my/reservations';
import { Route as _MyReviewsRoute } from '../pages/my/reviews';
import { Route as _MySettingsRoute } from '../pages/my/settings';

declare module '@granite-js/react-native' {
  interface RegisterScreen {
    '/_404': ReturnType<typeof _404Route.useParams>;
    '/about': ReturnType<typeof _AboutRoute.useParams>;
    '/faq': ReturnType<typeof _FaqRoute.useParams>;
    '/': ReturnType<typeof _IndexRoute.useParams>;
    '/portfolio': ReturnType<typeof _PortfolioIndexRoute.useParams>;
    '/portfolio/:id': ReturnType<typeof _PortfolioIdRoute.useParams>;
    '/quote/builder': ReturnType<typeof _QuoteBuilderRoute.useParams>;
    '/quote/:id': ReturnType<typeof _QuoteIdRoute.useParams>;
    '/reservation': ReturnType<typeof _ReservationIndexRoute.useParams>;
    '/reservation/search': ReturnType<typeof _ReservationSearchRoute.useParams>;
    '/reviews': ReturnType<typeof _ReviewsIndexRoute.useParams>;
    '/reviews/write/:reservationId': ReturnType<typeof _ReviewsWriteReservationIdRoute.useParams>;
    '/unauthorized': ReturnType<typeof _UnauthorizedRoute.useParams>;
    '/my': ReturnType<typeof _MyIndexRoute.useParams>;
    '/my/reservations': ReturnType<typeof _MyReservationsRoute.useParams>;
    '/my/reviews': ReturnType<typeof _MyReviewsRoute.useParams>;
    '/my/settings': ReturnType<typeof _MySettingsRoute.useParams>;
  }
}
